# Generated by Django 4.2 on 2023-05-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(default=0.0)),
                ('publish_date', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
